#!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
./bin/pre-commit-accessibility.sh
OUTPUT=$?
if [ $RESULT -ne 0 ] || [ $OUTPUT -ne 0 ]; then
  exit 1  # Fail pre-commit hook if any sc1ipt fails
fi
exit 0
