#!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
./pre-commit-accessibility.sh
OUTPUT=$?
if [ $RESULT -ne 0 ] || [ $OUTPUT -ne 0 ]; then
  exit 1  # Fail pre-commit hook if any script fails
fi
exit 0
